---
- file: state=directory path={{ graphite_target_dir }}/{{ item }}
  with_items: [ "{{ graphite_target_dir }}", "{{ graphite_repos_dir }}" ]

- name: download graphite packages
  git: repo=https://github.com/graphite-project/{{ item }}
       version={{ graphite_version }}
       dest={{ graphite_repos_dir }}/{{ item }}
       depth=1
  with_items: graphite_packages

- name: workaround for network blocking git://
  command: sed -i -e "s/git+git/git+https/" {{ graphite_repos_dir }}/{{ item }}/requirements.txt
  with_items: graphite_packages

- name: install graphite deps
  pip: requirements={{ graphite_repos_dir }}/{{ item }}/requirements.txt
       virtualenv={{ graphite_virtualenv }}
  with_items: graphite_packages

- name: set install dir
  lineinfile: dest={{ graphite_repos_dir }}/{{ item }}/setup.cfg
               state=present
               regexp=^prefix.*
               line=prefix={{ graphite_target_dir }}
               backup=yes
  when: item != "ceres"
  with_items: graphite_packages

- name: setup graphite apps
  command: chdir={{graphite_repos_dir }}/{{ item }}
           {{ graphite_python }} setup.py build install
  with_items: graphite_packages

